require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.3.6
  NewCops: enable
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/LineLength:
  Max: 120
  Exclude:
    - config/**/*
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Lint/MissingSuper:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - config/routes.rb
    - config/initializers/*
    - spec/**/*
Metrics/MethodLength:
  Max: 25
Metrics/ClassLength:
  Max: 100
Naming/VariableNumber:
  Enabled: false
Style/ArgumentsForwarding:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SafeNavigationChainLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Style/HashConversion:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/MixinGrouping:
  EnforcedStyle: grouped
Style/OpenStructUse:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Rails/ActionOrder:
  Enabled: false
Rails/DurationArithmetic:
  Enabled: false
Rails/EnumSyntax:
  Enabled: false
Rails/ThreeStateBooleanColumn:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Rails/WhereRange:
  Enabled: false
