default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  min_messages: warning
  password: postgres
  pool: 1
  username: postgres

development:
  <<: *default
  database: homey_project_tracker_development

test:
  <<: *default
  database: homey_project_tracker_test

production:
  <<: *default
  database: homey_project_tracker_production
  min_messages: warning
  pool: <%= Integer(ENV.fetch('DB_POOL', 5)) %>
  sslmode: require
  timeout: 5000
